### ISSUE TITLE
Guia de instalación / configuración

### ISSUE THREAD

**Issue by 0xNacho** [santiago-hernaez/Proyecto-Fin-Master-Scala#1]
Hola! :)

Cómo me puedo descargar el proyecto para probarlo? Hay que confiugrar / instalar alguna dependencia demás del propio proyecto?

Quizás estaría bien unas pequeñas instrucciones en el README.md

**Comment by santiago-hernaez** [comment]
Hola, 
he añadido una pequeña descripción del proyecto e instalación. 
No he podido añadir mas de momento; se irá ampliando con el tiempo.
